permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
paginate: 10
paginate_path: ":num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      styles : [highlight.css,post.css]
      scripts : [post.js]



title: "ğŸƒ leaf fly"
email: "sherlock@bakerstreet.club"
description: "é€» è¾‘ çš„ æ—‹ å¾‹ ç‰µ åŠ¨ ç° è±¡ ï¼Œ æ°¸ è¿œ æ¼” å¥ è€… äº‹ å® ã€‚"
github_username:  "laiyefei"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"




url: "http://laiyefei.com"
imgrepo: "http://laiyefei.com/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
